site_name: Moje projekty
site_author: Piotr Pawłowski
site_description: >-
    Portfolio moich projektów z Data Science i AI!

site_url: https://piotrek88.github.io/portfolio/

repo_name: Piotrek88/portfolio
repo_url: https://github.com/Piotrek88/portfolio

theme:
  name: material
  palette:
    primary: deep red

nav:
  - O mnie: index.md
  - Poprzednie projekty:
    - "Titanic": Titanic/index.md
    - "Iris": Iris/index.md