site_name: Moje projekty
site_author: Piotr Pawłowski
site_url: https://github.com/Piotrek88/portfolio
site_description: >-
    Portfolio moich projektów z Data Science i AI!

repo_name: Piotrek88/portfolio
repo_url: https://github.com/Piotrek88/portfolio

theme:
  name: material
  palette:
    primary: red

nav:
  - O mnie: index.md
  - Poprzednie projekty:
    - "Creative Paintings": Creative Paintings/index.md
    - "Łowca Danych": Łowca Danych/index.md
    - "Titanic": Titanic/index.md
    - "Iris": Iris/index.md