[project]
name = "portfolio"
version = "0.1.0"
description = ""
authors = []
readme = "README.md"
requires-python = ">=3.12"


[tool.poetry]
package-mode = false


[tool.poetry.dependencies]
mkdocs = "^1.6.1"
mkdocs-material = "^9.6.7"
jupyterlab = "^4.3.5"
nbconvert = "^7.16.6"
